#! /bin/bash

# Details to deploy client to github pages
GITHUB_USER_NAME='d-w-d'
GITHUB_REPO_NAME='world-daylight-map'
BASE_HREF=$GITHUB_REPO_NAME
SED=gsed

echo -e """ \033[32m
===========================
DEPLOYING BUNDLES TO GITHUB
BASE_HREF : \033[36m${BASE_HREF} \033[32m
=========================== \033[0m
"""

#################################################
### LOGIC WITHIN example
#################################################

### Move into example
cd example

### Build stuff
npm run build

### Copy images to dist so we can reference them direct from github pages
cp -R images dist

### Make sure you have a modern version of sed (viz. gsed on Mac)
if [[ ! $(command -v $SED) ]]; then
  echo """

    gsed not found!

    If you're on Mac then install with \`brew install gsed\`
    Else, change \$SED to point to a modern version of sed

  """
  exit 1
fi

### Change paths in index.html to reflect non-root base-href
$SED -i 's*href="/*href="/world-daylight-map/*g' dist/index.html
$SED -i 's*src="*src="/world-daylight-map/*g' dist/index.html

### Move back to root dir
cd ..

#################################################
### DEPLOY TO GITHUB
#################################################

### Build commmand gh-pages to deploy
read -r -d '' NODECMD <<EOM
  const ghpages = require("gh-pages");
  ghpages.publish("example/dist", function (err) {
    if (!!err) {
      console.log("OH NO! STH WENT WRONG :(", err);
      process.exit(1);
    }
    console.log("DEPLOYED TO: https://${GITHUB_USER_NAME}.github.io/${GITHUB_REPO_NAME}/");
  })
EOM

### Execute node code
node -e "$NODECMD"
